#!/bin/bash

#Проверка обновлений и установка модулей LAMP
sudo -s
apt-get update 
apt-get -y install apache2
apt-get -y install nginx
apt-get -y install php7.3 php7.3-mysql libapache2-mod-php7.3 php7.3-cli php7.3-cgi php7.3-gd php-dom 7.3
apt-get -y install mariadb-server

#Авто
mysql_secure_installation <<EOF
n
n
n
n
n
EOF

#Wordpress download and tar
cd /tmp
wget -c http://wordpress.org/latest.tar.gz 
tar -xzvf latest.tar.gz
rsync -av wordpress/* /var/www/html/
chown -R www-data:www-data /var/www/html/
chmod -R 755 /var/www/html/
rm /var/www/html/index.html

#Создание базы и пользователя marinadb
echo "CREATE DATABASE wp_database;" > /tmp/createDB.sql
echo "CREATE USER 'wp_user'@'localhost' IDENTIFIED BY '1234';" >> /tmp/createDB.sql
echo "GRANT ALL PRIVILEGES ON wp_database.* TO 'wp_user'@'localhost';" >> /tmp/createDB.sql
echo "FLUSH PRIVILEGES;" >> /tmp/createDB.sql

#Исправление файлов конфигураций Apache2
mysql -sfu root < "/tmp/createDB.sql"
cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/project.conf
grep -rl "#ServerName www.example.com" /etc/apache2/sites-available/project.conf | xargs perl -p -i -e 's/#ServerName www.example.com/ServerName www.project.com/g'
grep -rl "Listen 80" /etc/apache2/ports.conf | xargs perl -p -i -e 's/Listen 80/Listen 8080/g'
a2ensite project.conf
systemctl reload apache2

#Исправление файлов конфигураций nginx
echo 'server {' > /etc/nginx/sites-available/project
echo 'server_name project1.com;' >> /etc/nginx/sites-available/project
echo 'location / {' >> /etc/nginx/sites-available/project
echo 'proxy_set_header   X-Forwarded-For $remote_addr;' >> /etc/nginx/sites-available/project1\
echo 'proxy_set_header   Host $http_host;' >> /etc/nginx/sites-available/project
echo 'proxy_pass         "http://127.0.0.1.8080";' >> /etc/nginx/sites-available/project
echo '}' >> /etc/nginx/sites-available/project1
echo '}' >> /etc/nginx/sites-available/project1

#Удаление default  и привязка
rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default
ln /etc/nginx/sites-available/project /etc/nginx/sites-enabled/project

systemctl reload nginx
